"""Build the part of a handoff that never needed a model to write it.

A compaction summary is a model reading a transcript and retyping what it
thinks matters. Most of what it drops is not judgement at all: the user's own
words, the paths that were edited, the commands that failed, the branch it is
on. That material is sitting in the JSONL in machine-readable form, and a model
paraphrasing it can only lose fidelity. So this reads the transcript and emits
it directly, and the model's budget is freed for the part that does need
judgement.

Four sections, in the order a continuation needs them:

- **User turns**, verbatim. Including `AskUserQuestion` answers, which are the
  trap this script exists to avoid: in the bench fixture the operator's four
  scoping decisions - the ones the whole session turns on - arrive as a
  `tool_result`, not as a user turn. An appendix that quoted only user turns
  would carry one message and miss every decision in the conversation.
- **Tool ledger**: files written, commands run and how they ended, agents spawned.
- **Session state**: branch, worktree, PRs, background tasks, env flags, each
  labelled with whether it came from the transcript or from asking git now.
- Optionally a **marker pass** over a model-written summary, tagging every
  path, id, URL and version string the transcript does not contain. Tagged,
  never deleted: an unsourced claim may still be true, and the reader decides.

    python3 bench/appendix.py <transcript.jsonl> --lines 181
    python3 bench/appendix.py <transcript.jsonl> --lines 181 --summary handoff.md

`--lines` is the same cut `source.py` takes and for the same reason: the bench
appends its own turns to the fixture, so the file on disk outgrows the file the
arms were asked about.
"""

import argparse
import json
import os
import re
import subprocess
import sys

PASTE_CAP = 4000
COMMAND_CAP = 300
ERROR_CAP = 200

# A user record carrying one of these is the harness talking, not the user. The
# summary is asked for the human's words, and a handoff that quotes a task
# notification back at the next session has spent its most valuable section on
# machine chatter.
WRAPPERS = (
    "<cross-session-message",
    "[SYSTEM NOTIFICATION",
    "<task-notification>",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running",
    "<local-command-stdout>",
    "<command-name>",
    "<<autonomous-loop",
)

REMINDER = re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL)
BACKGROUND_ID = re.compile(r"background with ID: (\w+)", re.IGNORECASE)
AGENT_ID = re.compile(r"\b(a[0-9a-f]{6,}[\w-]*)\b")
# Anchored at the start of a command or straight after `export`/`env`, because a
# bare NAME=value scan matches f-string internals inside `python3 -c` and reports
# `STOP={'claude'...` as an environment variable this session set.
ENV_ASSIGN = re.compile(r"(?:^|;|&&|\|\||\bexport\s+|\benv\s+)\s*([A-Z][A-Z0-9_]{3,})=([^\s;&|]{0,40})", re.MULTILINE)

# Nothing in the JSONL says a command failed unless the tool set an error flag,
# and a warning written to stdout sets nothing. Recovering the cwd-reset failure
# in this fixture needs the text itself read for error shapes.
ERROR_SHAPE = re.compile(
    r"^.*\b(?:no such file or directory|command not found|permission denied|fatal:|error:|"
    r"warning:|traceback \(most recent call last\)|not found|cannot access)\b.*$",
    re.IGNORECASE | re.MULTILINE,
)
TICKET = re.compile(r"(?:PR|pull request|issue|#)\s*#?(\d{2,5})\b", re.IGNORECASE)
WORKTREE_PATH = re.compile(r"/home/[\w.\-]+/[\w./\-]*worktrees/[\w.\-]+")

# What the marker pass checks. Anything a reader would act on as fact and could
# look up: not prose, not adjectives, not the summary's opinions.
SPECIFICS = [
    ("url", re.compile(r"https?://[^\s`)\"'<>\]]+")),
    ("path", re.compile(r"(?<![\w/])(?:/[\w.\-]+){2,}/?|(?<![\w/])[\w.\-]+/[\w.\-/]*\.\w{1,5}\b")),
    ("ticket", re.compile(r"#\d{2,5}\b")),
    ("utterance", re.compile(r"\bop:[\w\-]+")),
    ("version", re.compile(r"\bv?\d+\.\d+\.\d+\b")),
]


def clip(text, cap, line=None):
    text = text.strip()

    if len(text) <= cap:
        return text

    tail = f"\n\n[... {len(text) - cap:,} more chars"
    tail += f"; full text at transcript line {line}]" if line else "]"

    return text[:cap] + tail


def records_of(path, lines):
    """Every record, with the 1-based line it sat on, up to the cut."""
    found = []

    with open(path, encoding="utf-8") as handle:
        for number, line in enumerate(handle, start=1):
            if lines is not None and number > lines:
                break

            line = line.strip()

            if not line:
                continue

            try:
                found.append((number, json.loads(line)))
            except json.JSONDecodeError:
                continue

    return found


def blocks_of(record):
    content = (record.get("message") or {}).get("content")

    if isinstance(content, str):
        return [{"type": "text", "text": content}]

    return content if isinstance(content, list) else []


def result_text(block):
    body = block.get("content")

    if isinstance(body, list):
        return "\n".join(p.get("text", "") for p in body if isinstance(p, dict))

    return str(body or "")


def is_wrapper(text):
    stripped = REMINDER.sub("", text).strip()

    if not stripped:
        return True

    return any(stripped.startswith(mark) or mark in stripped[:400] for mark in WRAPPERS)


def user_turns(records):
    """Real user speech, in order: typed turns and answered questions.

    Two rules, because the transcript marks the two halves differently.

    A typed turn carries `promptSource: "typed"` and `origin: {"kind": "human"}`,
    which is authoritative and beats reading the text for wrapper prefixes. The
    prefix list stays as the fallback for records written before those fields
    existed, and it is only consulted when they are absent.

    An AskUserQuestion answer carries neither: it is a tool_result, and nothing
    on it says the human chose those words, so it is matched by shape. Missing it
    is how an appendix ends up quoting one message from a conversation the user
    steered four times. In this fixture that one tool_result is where all four
    operator scoping decisions live.
    """
    found = []

    for number, record in records:
        if record.get("type") != "user" or record.get("isMeta"):
            continue

        source = record.get("promptSource")
        human = (record.get("origin") or {}).get("kind") == "human" if isinstance(record.get("origin"), dict) else False

        for block in blocks_of(record):
            if block.get("type") == "text":
                text = REMINDER.sub("", block.get("text", "")).strip()

                if not text:
                    continue

                if source is not None or human:
                    if source == "typed" or human:
                        found.append({"line": number, "kind": "typed", "text": text})
                elif not is_wrapper(text):
                    found.append({"line": number, "kind": "typed (inferred, no promptSource)", "text": text})

            elif block.get("type") == "tool_result":
                text = result_text(block)

                if text.startswith("Your questions have been answered:"):
                    found.append({"line": number, "kind": "answered questions", "text": text})

    return found


def tool_calls(records):
    """Every tool call paired with how it ended."""
    results = {}

    for number, record in records:
        for block in blocks_of(record):
            if block.get("type") == "tool_result":
                results[block.get("tool_use_id")] = {
                    "text": result_text(block),
                    "error": bool(block.get("is_error")),
                    "detail": record.get("toolUseResult"),
                }

    calls = []

    for number, record in records:
        if record.get("type") != "assistant":
            continue

        for block in blocks_of(record):
            if block.get("type") != "tool_use":
                continue

            calls.append({
                "line": number,
                "name": block.get("name"),
                "input": block.get("input") or {},
                "result": results.get(block.get("id")),
            })

    return calls


def outcome_of(call):
    """How a command ended, said only as strongly as the transcript supports.

    A shell exit code is not stored anywhere in the JSONL. What is stored is
    whether the tool reported an error and what went to stderr, so that is what
    this reports; calling it an exit code would be inventing a number.

    That is not enough on its own. In this fixture the command that failed
    because the Bash cwd resets between calls wrote `ugrep: warning: app/Models/:
    No such file or directory` to STDOUT, with an empty stderr and no error flag,
    so every mechanical signal the transcript carries says it succeeded. The last
    branch therefore reads the output for error shapes and reports the outcome as
    unmarked, which says what is known: the text looks like a failure and nothing
    in the record confirms it.
    """
    result = call.get("result")

    if result is None:
        return "no result recorded", ""

    detail = result.get("detail") if isinstance(result.get("detail"), dict) else {}
    stderr = str(detail.get("stderr") or "").strip()
    text = result["text"]

    if result["error"]:
        first = next((l for l in (stderr or text).splitlines() if l.strip()), "")

        return "error", clip(first, ERROR_CAP)

    if str(detail.get("interrupted")).lower() == "true":
        return "interrupted", ""

    if stderr:
        first = next((l for l in stderr.splitlines() if l.strip()), "")

        return "ok, wrote to stderr", clip(first, ERROR_CAP)

    shaped = ERROR_SHAPE.search(text[:4000])

    if shaped:
        return "unmarked, output reads as an error", clip(shaped.group(0).strip(), ERROR_CAP)

    return "ok", ""


# Written by the harness onto every record, not said by anyone in the session.
# The distinction is load-bearing on a re-homed bench fixture, where these five
# describe the copy rather than the conversation, and it is worth keeping in the
# real hook too: a summary that quotes the branch is quoting the envelope.
ENVELOPE_KEYS = ("branch", "cwd", "session", "permission mode", "cli version")


def transcript_state(records, calls):
    """Everything the transcript itself says about where the work is happening."""
    state = {
        "branch": set(),
        "cwd": set(),
        "session": set(),
        "permission mode": set(),
        "cli version": set(),
        "tickets referenced": set(),
        "background tasks": set(),
        "env and flags": set(),
        "worktree paths mentioned": set(),
    }

    for _, record in records:
        for key, field in (("branch", "gitBranch"), ("cwd", "cwd"), ("session", "sessionId"),
                           ("permission mode", "permissionMode"), ("cli version", "version")):
            value = record.get(field)

            if isinstance(value, str) and value:
                state[key].add(value)

    haystack = []

    for call in calls:
        command = call["input"].get("command")

        if isinstance(command, str):
            haystack.append(command)

            for name, value in ENV_ASSIGN.findall(command):
                # A shell value never opens with a bracket or a quote; a Python
                # dict literal inside an embedded script always does.
                if value[:1] in "{([\"'":
                    continue

                state["env and flags"].add(f"{name}={value}" if value else name)

        if call["result"]:
            haystack.append(call["result"]["text"][:4000])

        if call["input"].get("run_in_background"):
            state["background tasks"].add(f"{call['name']} at line {call['line']} (run_in_background)")

    for text in haystack:
        for found in BACKGROUND_ID.findall(text):
            state["background tasks"].add(found)

        for found in WORKTREE_PATH.findall(text):
            state["worktree paths mentioned"].add(found)

    for call in calls:
        if call["name"] in ("Agent", "Task"):
            agent = call["input"].get("subagent_type") or call["input"].get("description") or "agent"
            found = AGENT_ID.search(call["result"]["text"]) if call["result"] else None

            state["background tasks"].add(f"{agent} at line {call['line']}" + (f", id {found.group(1)}" if found else ", id not recorded"))

    for _, record in records:
        for block in blocks_of(record):
            if block.get("type") in ("text", "thinking"):
                body = block.get("text") or block.get("thinking") or ""

                for found in TICKET.findall(body[:20_000]):
                    state["tickets referenced"].add(f"#{found}")

    return state


def live_state(paths):
    """Ask git what is true now, for any worktree the transcript named that exists."""
    live = []

    for path in sorted(paths):
        if not os.path.isdir(path):
            live.append((path, "no longer exists on disk"))
            continue

        for label, argv in (("branch", ["rev-parse", "--abbrev-ref", "HEAD"]), ("uncommitted", ["status", "--short"])):
            try:
                done = subprocess.run(["git", "-C", path] + argv, capture_output=True, text=True, timeout=20)
                value = done.stdout.strip() or "(clean)"
            except Exception as error:
                value = f"could not be read: {error}"

            live.append((path, f"{label}: {clip(value, 600)}"))

    return live


def mark_unsourced(summary, transcript_text):
    """Tag specifics the transcript does not contain. Tagged, never deleted."""
    seen = transcript_text.lower()
    counts = {}
    spans = []

    for kind, pattern in SPECIFICS:
        for match in pattern.finditer(summary):
            token = match.group(0).rstrip(".,;:)`'\"")

            if len(token) < 4 or token.lower() in seen:
                continue

            spans.append((match.start(), match.start() + len(token), kind))

    spans.sort(key=lambda s: (s[0], -s[1]))

    kept = []
    reach = -1

    for start, end, kind in spans:
        if start < reach:
            continue

        kept.append((start, end, kind))
        reach = end

    out = []
    cursor = 0

    for start, end, kind in kept:
        counts[kind] = counts.get(kind, 0) + 1
        out.append(summary[cursor:end])
        out.append(" [unsourced]")
        cursor = end

    out.append(summary[cursor:])

    return "".join(out), counts


def render(records, calls, turns, state, live):
    out = []

    out.append("# Mechanical appendix")
    out.append("")
    out.append("Read directly from the session transcript, not written by a model. Nothing here")
    out.append("is paraphrased and nothing is judged; where the transcript is silent this says so.")
    out.append("")

    out.append("## Every user message, verbatim")
    out.append("")

    if not turns:
        out.append("_The transcript records no user speech before the cut._")

    for turn in turns:
        out.append(f"**Line {turn['line']} — {turn['kind']}**")
        out.append("")

        for line in clip(turn["text"], PASTE_CAP, turn["line"]).splitlines():
            out.append(f"> {line}")

        out.append("")

    out.append("## Tool ledger")
    out.append("")

    writes = [c for c in calls if c["name"] in ("Edit", "Write", "NotebookEdit", "MultiEdit")]
    shells = [c for c in calls if c["name"] == "Bash"]
    agents = [c for c in calls if c["name"] in ("Agent", "Task")]

    out.append(f"### Files written ({len(writes)})")
    out.append("")

    if not writes:
        out.append("_No file was created or edited in this transcript._")
    else:
        out.append("| line | tool | path |")
        out.append("| --- | --- | --- |")

        for call in writes:
            out.append(f"| {call['line']} | {call['name']} | `{call['input'].get('file_path', '(not recorded)')}` |")

    out.append("")
    out.append(f"### Commands run ({len(shells)})")
    out.append("")
    out.append("The JSONL stores no shell exit code, so `outcome` is what the tool reported,")
    out.append("not a number the transcript contains.")
    out.append("")
    out.append("| line | command | outcome | first error line |")
    out.append("| --- | --- | --- | --- |")

    for call in shells:
        command = clip(str(call["input"].get("command", "")).replace("\n", " ; "), COMMAND_CAP).replace("|", "\\|")
        outcome, first = outcome_of(call)

        out.append(f"| {call['line']} | `{command}` | {outcome} | {first.replace('|', chr(92) + '|')[:160]} |")

    out.append("")
    out.append(f"### Agents spawned ({len(agents)})")
    out.append("")

    if not agents:
        out.append("_No subagent was spawned in this transcript._")
    else:
        out.append("| line | type | description | id |")
        out.append("| --- | --- | --- | --- |")

        for call in agents:
            found = AGENT_ID.search(call["result"]["text"]) if call["result"] else None
            kind = call["input"].get("subagent_type", "(none)")
            what = clip(str(call["input"].get("description", "")), 80).replace("|", "\\|")

            out.append(f"| {call['line']} | {kind} | {what} | {found.group(1) if found else 'not recorded'} |")

    out.append("")
    out.append("## Session state")
    out.append("")
    out.append("`envelope` is metadata the harness stamps on every record; `stated` is something")
    out.append("said in the conversation itself; `live (read now)` is git answering today. A summary")
    out.append("that reports an envelope value is reporting where the file is, not what anyone said.")
    out.append("")
    out.append("| source | fact | value |")
    out.append("| --- | --- | --- |")

    for key, values in state.items():
        source = "envelope" if key in ENVELOPE_KEYS else "stated"

        if not values:
            out.append(f"| {source} | {key} | _nothing in the transcript states this_ |")
            continue

        for value in sorted(values):
            out.append(f"| {source} | {key} | `{clip(str(value), 200)}` |")

    for path, fact in live:
        out.append(f"| live (read now) | `{path}` | {fact.replace('|', chr(92) + '|')} |")

    out.append("")

    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("transcript")
    ap.add_argument("--lines", type=int, default=None, help="Only the first N records, the cut the fixture was built at.")
    ap.add_argument("--summary", default=None, help="A model-written handoff to mark up and print before the appendix.")
    ap.add_argument("--worktrees", nargs="*", default=[], help="Extra paths to read live git state from.")
    args = ap.parse_args()

    records = records_of(args.transcript, args.lines)

    if not records:
        sys.exit("no records read")

    calls = tool_calls(records)
    turns = user_turns(records)
    state = transcript_state(records, calls)
    live = live_state(set(args.worktrees) | state["worktree paths mentioned"])

    appendix = render(records, calls, turns, state, live)

    if not args.summary:
        print(appendix)

        return

    raw = "\n".join(json.dumps(r[1], ensure_ascii=False) for r in records)
    summary = open(args.summary, encoding="utf-8").read()
    marked, counts = mark_unsourced(summary, raw)

    print(marked)
    print()
    print(f"_Marker pass: {sum(counts.values())} specifics tagged `[unsourced]`"
          + (" (" + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())) + ")" if counts else "")
          + ". Tagged means the transcript does not contain the string, which is not proof it is false._")
    print()
    print(appendix)


if __name__ == "__main__":
    main()
